### ISSUE TITLE
R Kernel .ipynb Support not working

### ISSUE THREAD

**Issue by booysej** [booysej/soorgeon#1]
(ploomber) jacques@Jacquess-Macbook-Pro example3-refactor-r-notebook % soorgeon refactor eda-R.ipynb 
Error: Could not refactor notebook due to invalid syntax

 Traceback (most recent call last):
  File "/Users/jacques/opt/anaconda3/envs/ploomber/lib/python3.10/site-packages/soorgeon/export.py", line 442, in _check_syntax
    ast.parse(code)
  File "/Users/jacques/opt/anaconda3/envs/ploomber/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    colnames(df) = c('sepal_length', 'sepal_width','petal_length', 'petal_width', 'class')
    ^^^^^^^^^^^^
SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='?

(ploomber) jacques@Jacquess-Macbook-Pro example3-refactor-r-notebook % cd ..

**Comment by booysej** [comment]
[Ploomber/examples/example3-refactor-r-notebook/eda-R.ipynb](https://github.com/booysej/ds-personal/blob/main/Ploomber/examples/example3-refactor-r-notebook/eda-R.ipynb)

**Comment by booysej** [comment]
https://search.r-project.org/CRAN/refmans/lobstr/html/ast.html
